### ISSUE TITLE
Error in Rmd document

### ISSUE THREAD

**Issue by Robinlovelace** [PanosTsole87/odmsim#2]
This is the error I get, not sure why:

```
Quitting from lines 502-506 (Dissertation.Rmd) 
Error in names(x) <- value : 
  'names' attribute [5] must be the same length as the vector [4]
Calls: <Anonymous> ... source -> withVisible -> eval -> eval -> colnames<-
In addition: Warning messages:
1: In st_centroid.sf(Yorkshire1) :
  st_centroid assumes attributes are constant over geometries of x
2: One tm layer group has duplicated layer types, which are omitted. To draw multiple layers of the same type, use multiple layer groups (i.e. specify tm_shape prior to each of them). 
3: In st_centroid.sf(Yorkshire1) :
  st_centroid assumes attributes are constant over geometries of x
Execution halted
```

**Comment by PanosTsole87** [comment]
It seems that the newly updated "sf" package does not put the geometry column as last automatically. The problem with the code was that it was trying to subset all columns of an sf object except the second from last column which was not supposed to be geometry, but in that case it was. Because the object was still an sf the geometry column could not be actually removed, so the new subsetted object had the exact same number of columns as before. That is why when you tried to rbind the two sf objects you got an error as the two objects had a different number of columns.

**Comment by Robinlovelace** [comment]
Aha thanks for the explanation. I guess it shouldn't be too hard to fix. Let me know how you get on.

**Comment by PanosTsole87** [comment]
I fixed it (i think) and knitted the document successfully in my laptop. Committed the corrected code files as well. Could you try to knit it again?

**Comment by Robinlovelace** [comment]
Sure, will try it.

**Comment by Robinlovelace** [comment]
BTW here's how I updated my fork to match yours from the system terminal: https://asciinema.org/a/Utbql4mkCG148Q3T0T4ZHLGBs

**Comment by PanosTsole87** [comment]
Thanks Robin! Really interesting.

**Comment by Robinlovelace** [comment]
Confirmed, the issue is fixed! Closing this one. I get an error on line 722 though with the following message: 

```
Quitting from lines 722-727 (Dissertation.Rmd) 
Error in file(file, "rt") : cannot open the connection
Calls: <Anonymous> ... withVisible -> eval -> eval -> read.csv -> read.table -> file
In addition: There were 11 warnings (use warnings() to see them)
Execution halted
```

Any ideas? Great fix in any case.

**Comment by PanosTsole87** [comment]
Those column names are changing automatically when you read a csv in R, e.g. "16_24" becomes X.16_24. I guess I shouldn't start a column name with a number...Could you try again please? Btw I never got the latest error you got, so I am not sure if I fixed anything at all.

**Comment by Robinlovelace** [comment]
Trying it now...

**Comment by Robinlovelace** [comment]
Re-tried, still getting the same error. Maybe it's something downloaded on your computer not mine. Closing the original issue though.
